server:
  port: 8083

dubbo:
  protocol:
    port: -1
  registry:
    address: zookeeper://192.168.236.200:2181
  consumer:
    check: false
  application:
    name: stu-server

spring:
  datasource:
    url: jdbc:mysql:///db_stu?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver